altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  102de8a9-93b5-4507-a307-61cf1ce00438:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-03-19T04:24:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4c2c8e89-2f5c-4dcd-8c8c-d43d29df7ee1
            userCondition: null
            warning: null
            width: 100
        name: Obsah
        uid: aa4f8a35-0f7e-42ba-b231-9a80df5e335d
        userCondition: null
fs: authorImages
handle: authorImages
name: 'Author Images'
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
