defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 8ca35c29-3954-4faa-95bd-08f132b4cc12
handle: blog
maxAuthors: 1
name: Blog
propagationMethod: all
siteSettings:
  aabab36c-4448-4cd1-bb6e-1a4d7a7cf3f7:
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry.twig
    uriFormat: 'blog/{slug}'
type: channel
